### ISSUE TITLE
Will degap work well if the sequence of which is reverse complementary?

### ISSUE THREAD

**Issue by laijirong** [Jianwei-Zhang/DEGAP#5]
Thanks for developing such a powerful program.
I have some questions as below.
- The contigs that aligned to the reference genome is not in the same direction, which means some of the contigs is the reverse complementary sequences of the reference genome. I wonder if degap will handle this kind of situation well, have I to fix the direction of those contigs to fit the reference genome?
- In some complex cases, degap will run into an endless elongation, how can I find this situation and stop the program or adjust my squences or parameters?

**Comment by HuangYicheng-Bio** [comment]
> Thanks for developing such a powerful program. I have some questions as below.
> 
> * The contigs that aligned to the reference genome is not in the same direction, which means some of the contigs is the reverse complementary sequences of the reference genome. I wonder if degap will handle this kind of situation well, have I to fix the direction of those contigs to fit the reference genome?
> * In some complex cases, degap will run into an endless elongation, how can I find this situation and stop the program or adjust my squences or parameters?

1) If you're using GapFiller mode, then yes, you need to fix the direction; otherwise, if you're using CtgLinker mode, it is not necessary.
2) If DEGAP takes an excessive amount of time to run, you can check the output sequence of the last round in the process folder. This will help determine whether the delay is caused by extension errors due to highly similar regions in the genome or by inaccurate stop sequences that fail to terminate correctly. If you encounter extension errors, it could be due to the input seed sequences being affected by assembly errors or low quality. You can truncate some of the boundary sequences and then rerun the program. Additionally, you can control the extension length by setting the “—MaximumExtensionLength” parameter.

**Comment by laijirong** [comment]
Thank you so much for replying!

Best regards.
